[project]
name = "fastapi-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pushp Hans", email = "pushp.hans.official@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
fastapi-practice = "fastapi_practice:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
